cf apps | Select-String -pattern ssmembertransactionstatus-1-0-134
cf apps | Select-String -pattern IDontExist
cf apps | Select-String -pattern familymbrenrollment-5-2-31
cf apps | Select-String -pattern IDontExistExecptForTesting_ShowABlankLine-with-the-service-name
cf apps | Select-String -pattern dwnldmbrlist-5-2-21
cf apps | Select-String -pattern ssmembermaintain-1-2-20
cf apps | Select-String -pattern ebssdocumentarchive-5-2-19
cf apps | Select-String -pattern userprofile-5-2-12
cf apps | Select-String -pattern mbrshputility-5-2-42
cf apps | Select-String -pattern ebssbff-5-2-43
cf apps | Select-String -pattern mbrshperrorworkflow-5-2-16
cf apps | Select-String -pattern ssmemberinquiry-1-1-106
cf apps | Select-String -pattern ssmemberenrollment-1-1-19
cf apps | Select-String -pattern wmsmembererrorworkflow-5-2-0
cf apps | Select-String -pattern membermaintain-5-2-47
cf apps | Select-String -pattern membermrnsearchv2-5-2-32
cf apps | Select-String -pattern groupinformation-5-2-19
cf apps | Select-String -pattern ssusermanagement-1-2-28
cf apps | Select-String -pattern membersearch-5-1-61
cf apps | Select-String -pattern membertransHist-5-2-51
cf apps | Select-String -pattern ebssmassenrollment-5-2-19
cf apps | Select-String -pattern memberappsaveretrieve-5-2-36
cf apps | Select-String -pattern wls-1-0-6